#!/bin/bash
#SBATCH -J F_allP 
##SBATCH -o slurm.out
##SBATCH -e slurm.err
#SBATCH -t 48:00:00 
#SBATCH -n 40 -N 1
#SBATCH -p hbm-long-96core
#SBATCH --mail-type=BEGIN,END
#SBATCH --mail-user=lakshmanji.verma@stonybrook.edu 


echo "# of processors 40"

which python 
alias activate='/gpfs/projects/DillGroup/Lakshman/Software/Anaconda3/envs/python3/bin/activate'
conda activate python3
which python

SECONDS=0 

python genetic_opt.py 100000 #test

f=3600
Hrs=$(echo $SECONDS $f | awk '{printf "%10.6f\n",$1/$2}')
echo "Time taken by python code = $Hrs hours"

echo "Time taken by python code = $SECONDS seconds"

#python --version
#source activate python2.7
#python --version
#
#python cal_hbond_MDA.py ../md.gro ../center.xtc 
~                                                     
